### ISSUE TITLE
payload not selectable at runtime

### ISSUE THREAD

**Issue by shuffle2** [shuffle2/rockbox_psgroove#7]
Would be great to have some way to:
- Not compile in any payload
- Select any payload, or the JIG auth mode at runtime, similar to psfreedom
- Asbestos should be considered a special case: it needs stage2 present.

Posting here in hopes someone else will do it, because I won't :)

My idea would be to simply list the files present in some directory under .rockbox, which would contain all the payload files. Add a few more options for jig mode, etc...and done. Not too hard, just takes time...

**Comment by CrashSerious** [comment]
are you thinking via a plugin in rockbox or a config file?

The config file could be easy, with a plugin coming later. (I need to find good links for rockbox plugins.)
